{% set version = "0.0.1" %}

package:
  name: whitebox
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/WhiteBox/WhiteBox-{{ version }}.tar.gz
  sha256: f3832918bc3c66617f92e35f5d70729187676313caa60c187eb0f28b8fe5e3b5

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - WhiteBox

about:
  home: https://github.com/KelianF/WhiteBox
  license: MIT
  summary: 'Getting image size from png/jpeg/jpeg2000/gif file'
  description: |
    Helpful backtesting and signal processing tool
  dev_url: https://github.com/KelianF/WhiteBox
  doc_url: https://pypi.python.org/pypi/imagesize
  doc_source_url: https://github.com/KelianF/WhiteBox/blob/master/README.rst