{% set version = "0.0.1" %}

package:
  name: whitebox
  version: {{ version }}

source:
  git_rev: master
  git_url: https://github.com/KelianF/WhiteBox.git

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - WhiteBox

about:
  home: https://github.com/KelianF/WhiteBox
  license: MIT
  summary: 'Getting image size from png/jpeg/jpeg2000/gif file'
  description: 'Helpful backtesting and signal processing tool'
