{% set version = "0.0.2" %}

package:
  name: greybox
  version: {{ version }}

source:
  git_rev: master
  git_url: https://github.com/KelianF/GreyBox.git

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - WhiteBox

about:
  home: https://github.com/KelianF/GreyBox
  license: MIT
  summary: 'Help for quant finance'
  description: 'Helpful backtesting and signal processing tool'


